### ISSUE TITLE
Complete navigation on home page

### ISSUE THREAD

**Issue by pnicto** [crux-bphc/chronofactorem-rewrite#132]
These are not implemented right now except for a TODO comment because we don't have that route and tanstack router will yell at you for using a route that doesn't exist.

- [ ] Creating new timetable should take you to that page and let you edit
- [ ] On pressing edit button should take you to the edit page
- [ ] Decide the navigation for viewing a timetable(is the entire card clickable or only the name)
	- [ ] Decide on card hover color

https://github.com/crux-bphc/chronofactorem-rewrite/pull/114#issuecomment-1873273344

**Comment by soumitradev** [comment]
These are now done in various PRs, mostly the edit page PR
