### ISSUE TITLE
Seems to reload full page every time you shift tabs

### ISSUE THREAD

**Issue by Divyateja04** [crux-bphc/chronofactorem-rewrite#160]
Issue: Reloads full page upon shifting tabs or windows, causing multiple network requests as well. Upon speaking to @pnicto, it has been concluded that the content is being refreshed but maybe there can be a different way.

![image](https://github.com/crux-bphc/chronofactorem-rewrite/assets/28446977/61a2744a-0852-4d52-ada4-594d560b6747)

Procedure to replicate: Open any timetable on chrono and shift tabs and then go to the same page, it reloads the full page

**Comment by soumitradev** [comment]
fixed in latest patch
