### ISSUE TITLE
Timetable discrepancies with ERP

### ISSUE THREAD

**Issue by HemanthK-12** [crux-bphc/chronofactorem-rewrite#216]
Expected Behavior
Chronofactorem timetable should reflect ERP timetable, making it accurate in using at time of registration.In addition, CS F372 : OPERATING SYSTEMS T2 should be Tue 11:00AM - 11:50AM I015.
![image](https://github.com/user-attachments/assets/52a8f31d-b719-470d-b1c0-814d77707964)

Current Behavior
CS F372 : OPERATING SYSTEMS T2 is given Wed 8:00AM - 9:00AM D313.
Discrepanices also noticed in all other tuts of CS F372 and could be true for other courses as far as I know.
![image](https://github.com/user-attachments/assets/0f6d3596-7438-4c4b-aa75-af2ae229bdf8)

Possible Solution
Tying to sync with the latest courses and classes list in erp can fix the issue.

Steps to Reproduce
Create Timetable in a CS student account in 3rd year
Click CS F372 OPERATING SYSTEMS CDC and select T2 under Tutorial section.
Verify with ERP's course timings and discrepancy will be evident.
Context (Environment)
I just saw Mudit's post in FEG and wanted to sync my Chrono timetable with my google calendar but can't sync it now as there is no way to edit the timings and wrong timetable will be copied. It may be easy to change timings of one class but hard if others are also affected.

**Comment by skoriop** [comment]
Hi, thanks a lot for reporting this! 

We've updated the database and backend to reflect this change using the new timetable update endpoint. Please check if it's resolved now.

**Comment by soumitradev** [comment]
Closing this and #217 since it is resolved.
