### ISSUE TITLE
Project Type Courses

### ISSUE THREAD

**Issue by Shooooooonak** [crux-bphc/chronofactorem-rewrite#81]
Hii, first of all, I wanna appreciate this very cool and convenient initiative, great work! 

Although while using chrono, here are a few things I noticed:

- While registering for project type courses (all types, all degrees), they are associated with midsem and compare dates(that arent supposed to) which causes undesirable clashes with other courses
- They also have allotted lecture hours which cause clashes, so the user cannot design a draft timetable in such a situation
- Not an issue but it would be great if users can be given the option to colour code the courses on their timetable as they wish, would enhance the readability by a lot

Please do look into it, TIA!

**Comment by divok11231** [comment]
Hey! We have taken notice of these issues and we will be addressing them in the future. We would also appreciate if you could edit the issue body to only contain the points related to project type courses. If you could create a new issue for the color coding thing, that would be perfect. Separating the scope of these issues helps quite a bit with the flow of development for our projects.

**Comment by majimearun** [comment]
Hi @Shooooooonak, thanks for bringing it up, we believe we have now fixed the issue, and form the next release (the one for the upcoming semester) you can pick any of these courses without clashes (lecture times or exam times).

However if it comes up again, please reopen this issue and mention the course code and name.
