### ISSUE TITLE
Change of programme

### ISSUE THREAD

**Issue by pIyer314** [crux-bphc/chronofactorem-rewrite#84]
I logged in with a different programme for fun and I'm unable to change to AA . F

**Comment by soumitradev** [comment]
Hi @pIyer314, this will be fixed in the next release of ChronoFactorem. Meanwhile, if you still need your degree changed on Chrono, please email us at [crux@hyderabad.bits-pilani.ac.in](mailto:crux@hyderabad.bits-pilani.ac.in)
