### ISSUE TITLE
CDC Compre clashing with another CDC

### ISSUE THREAD

**Issue by bomb-rajas** [crux-bphc/chronofactorem-rewrite#88]
CHEM F241(Inorganic chemistry-2) and CHEM F242(Chemical Experimentation-1) subjects are the CDCs of Msc. Chem, which it's showing on chrono that the compre dates clash. One is a lab course(F242), and the hence compre date isn't mentioned in the draft time table. But chrono has somehow assumed it to be clashing with Inorganic chem.

**Comment by majimearun** [comment]
Same fix as #81
