### ISSUE TITLE
Cant change branch after selecting one.

### ISSUE THREAD

**Issue by Aerialsamurai** [crux-bphc/chronofactorem-rewrite#89]
I chose wrong branch when I made the chronofactoreum account and now I am not able to change it. Pls fix this issue

**Comment by soumitradev** [comment]
Hi @Aerialsamurai, this will be fixed in the next release of ChronoFactorem. Meanwhile, if you still need your degree changed on Chrono, please email us at crux@hyderabad.bits-pilani.ac.in
